---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql
  labels:
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/name: mysql
secrets:
  - name: mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/name: mysql
type: Opaque
data:
  mysql-root-password: cm9vdA==
  mysql-user-password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/name: mysql
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/name: mysql
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/name: mysql
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/name: mysql
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/name: mysql
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: mysql
      app.kubernetes.io/name: mysql
  serviceName: mysql-headless
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: primary
        app.kubernetes.io/instance: mysql
        app.kubernetes.io/name: mysql
    spec:
      containers:
        - name: mysql
          image: docker.io/bitnami/mysql:5.7.36-debian-10-r13
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-root-password
                  name: mysql
            - name: MYSQL_DATABASE
              value: prizmdb
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-user-password
                  name: mysql
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: mysql-data
              mountPath: /bitnami/mysql
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - '-ec'
                - |
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  mysqladmin status -uroot -p"${password_aux}"
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - '-ec'
                - |-
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  mysqladmin status -uroot -p"${password_aux}"
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            exec:
              command:
                - /bin/bash
                - '-ec'
                - |-
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  mysqladmin status -uroot -p"${password_aux}"
            failureThreshold: 10
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      serviceAccountName: mysql
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
        labels:
          app.kubernetes.io/component: primary
          app.kubernetes.io/instance: mysql
          app.kubernetes.io/name: mysql
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
